### ISSUE TITLE
PHP Default types are getting Spatie namespace Laravel Homestead

### ISSUE THREAD

**Issue by seymourduncandevops** [spatie/analytics-statistics#3]
Hey there,

I'm trying to set this up on Laravel 5.2 on homestead (using HHVM hack) but have been running into a lot of issues. With a default setup (following readme install instructs to the letter), I get this error out of the box:

```
ErrorException in AnalyticsClient.php line 39:
Argument 1 passed to Spatie\Analytics\AnalyticsClient::setCacheLifeTimeInMinutes() must be an instance of Spatie\Analytics\int, int given
```

Even after removing all type hinting from the spatie/ files, other odd issues seem to arise in Carbon which makes me think this issue is deeper than some duckpunching patches. Any thoughts on how to resolve?

**Comment by freekmurze** [comment]
Hi, 

I'm going to abandon this package soon.

if you're using Laravel 5, take a look at our newer [laravel-analytics](https://github.com/spatie/laravel-analytics) package.

**Comment by seymourduncandevops** [comment]
Hey, sorry, that was the package I was using, but made the issue in the wrong repo. I'll transfer this over. Thanks!
