### ISSUE TITLE
trying on laravel 4.2

### ISSUE THREAD

**Issue by johnef** [spatie/analytics-statistics#4]
composer require spatie/analytics-statistics
got Error.
Installation failed, reverting ./composer.json to its original content

**Comment by sebastiandedeyne** [comment]
Continuation from spatie/laravel-analytics#126

This package requires `nesbot/carbon: ^1.19`, and one of your other dependencies requires a lower version. You're going to have to find out which one and see if you can update it.

Alternatively, I'd accept a PR that requires a lower carbon version, and has passing tests.

**Comment by johnef** [comment]
@sebastiandedeyne but I am using Laravel 4.2 how can I update my `nesbot/carbon` ?
I tried to do so but got

```
Installation request for nesbot/carbon 1.21 -> satisfiable by nesbot/carbon[1.21.0].
    - Conclusion: remove symfony/translation v2.5.12
    - Conclusion: don't install symfony/translation v2.5.12
```

I even tried to install the version you pointed to `nesbot/carbon: ^1.19` but still the same can't be installed on older version for laravel!!

**Comment by sebastiandedeyne** [comment]
According to Laravel 4.2's `composer.json`, there's no restriction on Carbon 1.19, so I assume it's another dependency that's the culprit here.

https://github.com/laravel/framework/blob/v4.2.11/composer.json#L20

**Comment by johnef** [comment]
Maybe I didn't understand you right, I have the same nesbot/carbon version that you pointed to in the `v4.2.11/composer.json#L20`
in my `composer.lock` have `"nesbot/carbon": "~1.0"`
so what is the problem!!

**Comment by freekmurze** [comment]
Hi, it seems that this problem is not caused by our package. but by something specific to your project. Try to pinpoint which of your other packages require that specific older version of composer.
